INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Max', 'S', 3, 3, 3, 'Kuchenclan', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Felix M.', 'S', 4, 4, 3, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Melike', 'S', 5, 5, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Laura K.', 'S', 5, 4, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Lara', 'S', 7, 7, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Karin', 'S', 3, 4, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Asude', 'S', 7, 4, 6, 'TiaratanistIn', 'Kunst');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Valentin', 'S', 8, 3, 3, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Carlo', 'S', 9, 4, 6, 'Professor', 'Vize');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Tiara', 'S', 10, 5, 6, 'Musik', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Lydia', 'S', 9, 6, 6, 'TiaratanistIn', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Julius G.', 'S', 4, 4, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Karo', 'S', 5, 5, 5, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Julius T.', 'S', 2, 2, 1, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Aylina', 'S', 1, 3, 2, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Laura B.', 'S', 6, 4, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Fabian', 'S', 2, 3, 3, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Tanaz', 'S', 2, 3, 3, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Klara', 'S', 2, 2, 3, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Lucas', 'S', 4, 4, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Julika', 'S', 1, 2, 1, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Luis', 'S', 7, 6, 5, 'Kuchenclan', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Carrie', 'S', 8, 4, 5, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Felix B.', 'S', 4, 6, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Paula', 'S', 6, 5, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('David', 'S', 10, 6, 6, 'Schülersprecher', '');

INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Herr Weschke', 'L', 10, 7, 7, 'TiaratanistIn', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Herr Förster', 'L', 8, 6, 5, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Frau Schuhmann', 'L', 1, 2, 2, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Die Horbats', 'L', 6, 6, 6, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Herr Lapp', 'L', 7, 4, 5, 'TiaratanistIn', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Frau Raatz', 'L', 10, 5, 7, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Frau Schneeweiß', 'L', 7, 5, 5, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Herr Caspers', 'L', 5, 4, 4, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Frau Regul', 'L', 1, 2, 2, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Frau Teupen', 'L', 9, 8, 5, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Herr Monke', 'L', 10, 7, 5, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Frau Rheas', 'L', 10, 8, 8, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Herr Knoth', 'L', 10, 6, 6, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Herr Schoene', 'L', 1, 1, 1, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Herr Salinger', 'L', 9, 7, 5, '', '');
INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('Freu Nippe', 'L', 2, 2, 2, 'TiaratanistIn', '');

INSERT INTO eventCard(name, cost) VALUES ('Hallentraining', 3);
INSERT INTO eventCard(name, cost) VALUES ('Doppelstunde', 3);
INSERT INTO eventCard(name, cost) VALUES ('Instrumentengeklimper', 3);
INSERT INTO eventCard(name, cost) VALUES ('Schulschließung', 10);
INSERT INTO eventCard(name, cost) VALUES ('Lüge', 3);
INSERT INTO eventCard(name, cost) VALUES ('Binomische Formeln', 3);

INSERT INTO actionCard(name, cost) VALUES ('Beleidigung', 3);
INSERT INTO actionCard(name, cost) VALUES ('Unterrichtsgekicher', 3);
INSERT INTO actionCard(name, cost) VALUES ('Fick Dich', 3);
INSERT INTO actionCard(name, cost) VALUES ('Böse Gerüchte', 3);
INSERT INTO actionCard(name, cost) VALUES ('Mobbing', 3);
INSERT INTO actionCard(name, cost) VALUES ('Diskussion mit Herrn Knoth', 3);

-- INSERT INTO personCard(name, LS, cost, atk, dfp, role1, role2) VALUES ('');
-- INSERT INTO eventCard(name, cost) VALUES ('');
-- INSERT INTO actionCard(name, cost) VALUES ('');
